modLoader="javafml"
loaderVersion="[42,)"
license="All rights reserved"
[[mods]]
modId="l2world"
version="${file.jarVersion}" #mandatory
displayName="L2 World" #mandatory
logoFile="l2world.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2world]]
    modId="forge"
    mandatory=true
    versionRange="[42.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2world]]
    modId="l2complements"
    mandatory=true
    versionRange="[0.2.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.l2world]]
    modId="l2library"
    mandatory=true
    versionRange="[1.8.5,)"
    ordering="AFTER"
    side="BOTH"